### ISSUE TITLE
Aim + Fire Option is broken in 2P mode

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Arcade-Inferno_MiSTer#4]
When enabling Aim + Fire, player 2 controls P1's movements while P2 just shoots in the same direction. Aim + Fire works in 1P mode.

The workaround I'm using is disabling Aim + Fire and mapping fire to L2 and R2. It works pretty well

**Comment by birdybro** [comment]
Thanks for the report, looking into it now. :)

**Comment by birdybro** [comment]
Forgot to look into it actually, just fixed it. What a boneheaded mistake!

https://github.com/MiSTer-devel/Arcade-Inferno_MiSTer/commit/fcd20400c263332946924a2e7b79e97f8e0ca01e
